<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addfks extends Doctrine_Migration_Base
{
    public function up()
    {
//        $this->createForeignKey('account', 'account_id_token_account_id', array(
//             'name' => 'account_id_token_account_id',
//             'local' => 'id',
//             'foreign' => 'account_id',
//             'foreignTable' => 'token',
//             ));
//        $this->createForeignKey('account', 'account_id_user_trusted_client_account_id', array(
//             'name' => 'account_id_user_trusted_client_account_id',
//             'local' => 'id',
//             'foreign' => 'account_id',
//             'foreignTable' => 'user_trusted_client',
//             ));
        $this->createForeignKey('token', 'token_account_id_account_id', array(
             'name' => 'token_account_id_account_id',
             'local' => 'account_id',
             'foreign' => 'id',
             'foreignTable' => 'account',
             ));
        $this->createForeignKey('user_trusted_client', 'user_trusted_client_account_id_account_id', array(
             'name' => 'user_trusted_client_account_id_account_id',
             'local' => 'account_id',
             'foreign' => 'id',
             'foreignTable' => 'account',
             ));
        $this->createForeignKey('user_trusted_client', 'user_trusted_client_client_id_client_id', array(
             'name' => 'user_trusted_client_client_id_client_id',
             'local' => 'client_id',
             'foreign' => 'id',
             'foreignTable' => 'client',
             ));
    }

    public function down()
    {
//        $this->dropForeignKey('account', 'account_id_token_account_id');
//        $this->dropForeignKey('account', 'account_id_user_trusted_client_account_id');
        $this->dropForeignKey('token', 'token_account_id_account_id');
        $this->dropForeignKey('user_trusted_client', 'user_trusted_client_account_id_account_id');
        $this->dropForeignKey('user_trusted_client', 'user_trusted_client_client_id_client_id');
    }
}