<?php

/**
 * UserTrustedClientTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserTrustedClientTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserTrustedClientTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserTrustedClient');
    }
}