<?php

/**
 * RequestFileTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RequestFileTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RequestFileTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RequestFile');
    }
}